site_name: Compiladores
nav:
  - Home: index.md
  - "Prazer, Compiladores! 游뱋游": aula1.md
  - "Compila칞칚o e Intera칞칚o: Do C칩digo ao Execut치vel 游눹游댢": aula2.md
  - "An치lise L칠xica": aula3.md
  - "An치lise Sem칙ntica": aula4.md
theme:
  name: readthedocs